In [4]:
from tile import TileCoder
import numpy as np

# number of tile spanning each dimension
tiles_per_dim = [10, 10]
# value limits of each dimension
lims = [(0.0, 10.0), (0.0, 10.0)]
# number of tilings
tilings = 8

T = TileCoder(tiles_per_dim, lims, tilings)


In [5]:
# linear function weight vector
w = np.zeros(T.n_tiles)

# step size for SGD
alpha = 0.1 / tilings

# target function with gaussian noise
def target_fn(x, y):
  return np.sin(x) + np.cos(y) + 0.1 * np.random.randn()

# learn from 10,000 samples
for i in range(10000):
   # get noisy sample from target function at random location
  x, y = 2.0 * np.pi * np.random.rand(2)
  target = target_fn(x, y)
  # get prediction from active tiles at that location
  test = np.array(x,y)
  tiles = T[test]
  print(tiles)
  pred = w[tiles].sum()
  print(w[tiles])
  print(w[tiles].sum())
  # update weights with SGD
  w[tiles] += alpha * (target - pred)

[ 48 180 302 412 544 665 786 907]
[0. 0. 0. 0. 0. 0. 0. 0.]
0.0
[ 12 133 265 375 508 629 739 871]
[0. 0. 0. 0. 0. 0. 0. 0.]
0.0
[ 48 169 301 411 544 665 775 907]
[-0.00291859  0.          0.          0.         -0.00291859 -0.00291859
  0.         -0.00291859]
-0.011674358500575665
[ 24 145 266 387 508 629 750 871]
[0.         0.         0.         0.         0.02057526 0.02057526
 0.         0.02057526]
0.06172578225127114
[ 24 145 277 387 520 641 751 883]
[-0.0017026 -0.0017026  0.        -0.0017026  0.         0.
  0.         0.       ]
-0.005107796565285712
[ 24 145 277 387 508 640 751 872]
[-0.00432471 -0.00432471 -0.00262211 -0.00432471  0.01887266  0.
 -0.00262211  0.        ]
0.0006543008814379678
[ 60 192 314 424 556 677 798 919]
[0. 0. 0. 0. 0. 0. 0. 0.]
0.0
[ 36 169 290 411 532 653 774 895]
[ 0.         -0.02590688  0.         -0.02590688  0.          0.
  0.          0.        ]
-0.05181376602985082
[ 60 181 302 423 544 665 786 907]
[-0.01265497  0.         -0.00291859  0. 

In [6]:
a = np.array([1, 2, 3])
b = np.array([1])
c = np.concatenate((a, b))
print(a)
print(b)
print(c.tolist())

[1 2 3]
[1]
[1, 2, 3, 1]
